export const gradeTwoPhonemeAudio = {
  bSound: '/assets/audio/grade2/phonemes/b-sound.wav',
  chSound: '/assets/audio/grade2/phonemes/ch-sound.wav',
  dSound: '/assets/audio/grade2/phonemes/d-sound.wav',
  fSound: '/assets/audio/grade2/phonemes/f-sound.wav',
  gSound: '/assets/audio/grade2/phonemes/g-sound.wav',
  hardC: '/assets/audio/grade2/phonemes/hard-c.wav',
  hSound: '/assets/audio/grade2/phonemes/h-sound.wav',
  jSound: '/assets/audio/grade2/phonemes/j-sound.wav',
  lSound: '/assets/audio/grade2/phonemes/l-sound.wav',
  longA: '/assets/audio/grade2/phonemes/long-a.wav',
  longE: '/assets/audio/grade2/phonemes/long-e.wav',
  longI: '/assets/audio/grade2/phonemes/long-i.wav',
  longO: '/assets/audio/grade2/phonemes/long-o.wav',
  longU: '/assets/audio/grade2/phonemes/long-u.wav',
  mSound: '/assets/audio/grade2/phonemes/m-sound.wav',
  nSound: '/assets/audio/grade2/phonemes/n-sound.wav',
  pSound: '/assets/audio/grade2/phonemes/p-sound.wav',
  rSound: '/assets/audio/grade2/phonemes/r-sound.wav',
  sSound: '/assets/audio/grade2/phonemes/s-sound.wav',
  shSound: '/assets/audio/grade2/phonemes/sh-sound.wav',
  shortA: '/assets/audio/grade2/phonemes/short-a.wav',
  shortE: '/assets/audio/grade2/phonemes/short-e.wav',
  shortI: '/assets/audio/grade2/phonemes/short-i.wav',
  shortO: '/assets/audio/grade2/phonemes/short-o.wav',
  shortU: '/assets/audio/grade2/phonemes/short-u.wav',
  tSound: '/assets/audio/grade2/phonemes/t-sound.wav',
  thSound: '/assets/audio/grade2/phonemes/th-sound.wav',
  vSound: '/assets/audio/grade2/phonemes/v-sound.wav',
  wSound: '/assets/audio/grade2/phonemes/w-sound.wav',
  xSound: '/assets/audio/grade2/phonemes/x-sound.wav',
  zSound: '/assets/audio/grade2/phonemes/z-sound.wav',
} as const;

const instructionalSounds: Readonly<Record<string, string>> = {
  '/aɪ/': gradeTwoPhonemeAudio.longI,
  '/ɑ/': gradeTwoPhonemeAudio.shortO,
  '/æ/': gradeTwoPhonemeAudio.shortA,
  '/b/': gradeTwoPhonemeAudio.bSound,
  '/d/': gradeTwoPhonemeAudio.dSound,
  '/dʒ/': gradeTwoPhonemeAudio.jSound,
  '/eɪ/': gradeTwoPhonemeAudio.longA,
  '/ɛ/': gradeTwoPhonemeAudio.shortE,
  '/f/': gradeTwoPhonemeAudio.fSound,
  '/g/': gradeTwoPhonemeAudio.gSound,
  '/h/': gradeTwoPhonemeAudio.hSound,
  '/iː/': gradeTwoPhonemeAudio.longE,
  '/ɪ/': gradeTwoPhonemeAudio.shortI,
  '/juː/': gradeTwoPhonemeAudio.longU,
  '/k/': gradeTwoPhonemeAudio.hardC,
  '/ks/': gradeTwoPhonemeAudio.xSound,
  '/l/': gradeTwoPhonemeAudio.lSound,
  '/m/': gradeTwoPhonemeAudio.mSound,
  '/n/': gradeTwoPhonemeAudio.nSound,
  '/oʊ/': gradeTwoPhonemeAudio.longO,
  '/p/': gradeTwoPhonemeAudio.pSound,
  '/r/': gradeTwoPhonemeAudio.rSound,
  '/s/': gradeTwoPhonemeAudio.sSound,
  '/t/': gradeTwoPhonemeAudio.tSound,
  '/tʃ/': gradeTwoPhonemeAudio.chSound,
  '/v/': gradeTwoPhonemeAudio.vSound,
  '/w/': gradeTwoPhonemeAudio.wSound,
  '/z/': gradeTwoPhonemeAudio.zSound,
  '/ʃ/': gradeTwoPhonemeAudio.shSound,
  '/θ/': gradeTwoPhonemeAudio.thSound,
  '/ʌ/': gradeTwoPhonemeAudio.shortU,
};

export function getGradeTwoLetterSoundAudio(
  letter: string,
  soundLabel: string,
) {
  return (
    instructionalSounds[soundLabel] ??
    `/assets/audio/courses/${letter}/letter-sound.wav`
  );
}
